version = 0.1
[development]
[development.deploy]
[development.deploy.parameters]
stack_name = "serverless-wc-data"
s3_prefix = "serverless-wc-data"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
